pull in some good ideas from libranch (RIP)

diff --git a/bin/gcbm b/bin/gcbm
--- a/bin/gcbm
+++ b/bin/gcbm
@@ -3,19 +3,28 @@
 
 # git - create new branch that tracks origin/(main|master)
 
+current_git_branch () {
+  git rev-parse --abbrev-ref HEAD
+}
+in_git_repo () {
+  git status > /dev/null && return 0 || @echo-err "Not in git repo" && return 1
+}
+on_git_branch () {
+  [ "$(current_git_branch)" != "$1" ] && @echo-err ">_<  Must be on branch '$1' for this" && return 1 || return 0
+}
+
 new_branch_name="${1?:Must provide name of new branch}"
 
-# is the default branch main or master?
-# see https://stackoverflow.com/q/5167957
-if git show-ref --verify --quiet refs/heads/main
+if in_git_repo
 then
-  default_branch="main"
-elif git show-ref --verify --quiet refs/heads/master
-then
-  default_branch="master"
-else
-  echo "Error: default branch is not 'main' or 'master'"
-  exit 1
-fi
+  # what is the default branch?
+  # TODO: make this a badash function
+  if git show-ref --verify --quiet refs/heads/main; then default_branch="main"
+  elif git show-ref --verify --quiet refs/heads/master; then default_branch="master"
+  else echo "Error: default branch is not 'main' or 'master'"; exit 1; fi
 
-@wait-for-command git checkout -b "$new_branch_name" "origin/$default_branch"
+  if on_git_branch "$default_branch"
+  then
+    @wait-for-command git checkout -b "$new_branch_name" "origin/$default_branch"
+  fi
+fi
