tighten up this boilerplate

diff --git a/bin/gmmb b/bin/gmmb
--- a/bin/gmmb
+++ b/bin/gmmb
@@ -29,18 +29,11 @@ not_on_git_branch ()
 
 if in_git_repo && no_uncommitted_changes
 then
-  # is the default branch main or master?
-  # see https://stackoverflow.com/q/5167957
-  if git show-ref --verify --quiet refs/heads/main
-  then
-    default_branch="main"
-  elif git show-ref --verify --quiet refs/heads/master
-  then
-    default_branch="master"
-  else
-    @echo-err "Error: default branch is not 'main' or 'master'"
-    exit 1
-  fi
+  # what is the default branch?
+  # TODO: make this a badash function
+  if git show-ref --verify --quiet refs/heads/main; then default_branch="main"
+  elif git show-ref --verify --quiet refs/heads/master; then default_branch="master"
+  else echo "Error: default branch is not 'main' or 'master'"; exit 1; fi
 
   if not_on_git_branch "$default_branch"
   then
diff --git a/bin/gram b/bin/gram
--- a/bin/gram
+++ b/bin/gram
@@ -36,18 +36,11 @@ then
   branch_name=$(current_git_branch)
   need_to_remove_orig_files='no'
 
-  # is the default branch main or master?
-  # see https://stackoverflow.com/q/5167957
-  if git show-ref --verify --quiet refs/heads/main
-  then
-    default_branch="main"
-  elif git show-ref --verify --quiet refs/heads/master
-  then
-    default_branch="master"
-  else
-    echo "Error: default branch is not 'main' or 'master'"
-    exit 1
-  fi
+  # what is the default branch?
+  # TODO: make this a badash function
+  if git show-ref --verify --quiet refs/heads/main; then default_branch="main"
+  elif git show-ref --verify --quiet refs/heads/master; then default_branch="master"
+  else echo "Error: default branch is not 'main' or 'master'"; exit 1; fi
 
   if not_on_git_branch "$default_branch"
   then
diff --git a/bin/squash-branch b/bin/squash-branch
--- a/bin/squash-branch
+++ b/bin/squash-branch
@@ -80,18 +80,11 @@ commit_msg_extra_line="${2:-}"
 
 branch_name="$(current_git_branch)"
 
-# is the default branch main or master?
-# see https://stackoverflow.com/q/5167957
-if git show-ref --verify --quiet refs/heads/main
-then
-  default_branch="main"
-elif git show-ref --verify --quiet refs/heads/master
-then
-  default_branch="master"
-else
-  echo "Error: default branch is not 'main' or 'master'"
-  exit 1
-fi
+# what is the default branch?
+# TODO: make this a badash function
+if git show-ref --verify --quiet refs/heads/main; then default_branch="main"
+elif git show-ref --verify --quiet refs/heads/master; then default_branch="master"
+else echo "Error: default branch is not 'main' or 'master'"; exit 1; fi
 
 based_on="$(based_on_local_or_origin "$branch_name" "$default_branch")"
 
