include the commands I normally have to do before this

diff --git a/bin/gmmb b/bin/gmmb
--- a/bin/gmmb
+++ b/bin/gmmb
@@ -35,8 +35,15 @@ then
   # shellcheck disable=SC2154
   if not_on_git_branch "$default_branch"
   then
-    # merge straight from origin, without updating local main/master
-    if ! @wait-for-command git merge "origin/$default_branch"
+
+    starting_branch="$(current_git_branch)"
+
+    # try to update main branch and get back to the starting branch
+    @@SCRIPT-DIR@@/gcm && mint update && @@SCRIPT-DIR@@/gc "$current_git_branch"
+    @exit-on-error 'Error updating main branch and getting back to current branch'
+
+    # merge the updated commits from local main/master
+    if ! @wait-for-command git merge "$default_branch"
     then
       echo_info "Merge failed"
       @wait-for-keypress 'Press any key to start resolving conflicts (or Ctrl-C to abort)... '
