add annotations to check commands required to run the scripts

diff --git a/scripts/archive-page b/scripts/archive-page
--- a/scripts/archive-page
+++ b/scripts/archive-page
@@ -10,16 +10,21 @@ echo_err ()
 {
     echo -e "${COLOR_FG_RED}$@${COLOR_RESET}" 1>&2
 }
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check wget "search 'how to install wget'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 page_url="${1:?No URL entered}"
-requirements=( wget )
-all_reqs_ok="true"
-for executable in "${requirements[@]}"; do
-  if [ ! $(command -v $executable) ]; then
-    echo_err "'$executable' is required but not installed"
-    all_reqs_ok="false"
-  fi
-done
-if [ "$all_reqs_ok" == "false" ]; then
-  exit 1
-fi
 wget --wait=1 --random-wait --convert-links --page-requisites --user-agent="" "$page_url"
diff --git a/scripts/chrome-tabs b/scripts/chrome-tabs
--- a/scripts/chrome-tabs
+++ b/scripts/chrome-tabs
@@ -4,4 +4,26 @@
 # the file script-gen/chrome-tabs, and run './generate-scripts.sh'
 ###########################################################################
 
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check uniq "search 'how to install uniq'"
+combined_return=$(( combined_return + $? ))
+requirement_check grep "search 'how to install grep'"
+combined_return=$(( combined_return + $? ))
+requirement_check sort "search 'how to install sort'"
+combined_return=$(( combined_return + $? ))
+requirement_check strings "search 'how to install strings'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 strings "$HOME/Library/Application Support/Google/Chrome/Default/Current Session" | grep -E '^https?://' | sort | uniq
diff --git a/scripts/eslint-for-vim b/scripts/eslint-for-vim
--- a/scripts/eslint-for-vim
+++ b/scripts/eslint-for-vim
@@ -4,4 +4,20 @@
 # the file script-gen/eslint-for-vim, and run './generate-scripts.sh'
 ###########################################################################
 
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check npx "search 'how to install npx'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 npx --no-install eslint "$@" 2>/dev/null || echo "v1.0.0"
diff --git a/scripts/libranch b/scripts/libranch
--- a/scripts/libranch
+++ b/scripts/libranch
@@ -53,6 +53,22 @@ echo_info ()
 {
     echo -e "${COLOR_FG_BOLD_BLUE}$@${COLOR_RESET}" 1>&2
 }
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check git "search 'how to install git'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 new_branch_name="$1"
 if [ -z "$new_branch_name" ]
 then
diff --git a/scripts/lines-of-code b/scripts/lines-of-code
--- a/scripts/lines-of-code
+++ b/scripts/lines-of-code
@@ -4,6 +4,24 @@
 # the file script-gen/lines-of-code, and run './generate-scripts.sh'
 ###########################################################################
 
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check grep "search 'how to install grep'"
+combined_return=$(( combined_return + $? ))
+requirement_check sed "search 'how to install sed'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 valid_files=( $(echo "$@" | sed -E 's/[^[:space:]]+.swp\ //g') )
 all_files="$(cat ${valid_files[*]})"
 all_files_no_blank="$(echo "$all_files" | sed '/^[[:space:]]*$/d')"
diff --git a/scripts/lireview b/scripts/lireview
--- a/scripts/lireview
+++ b/scripts/lireview
@@ -49,18 +49,27 @@ echo_info ()
 {
     echo -e "${COLOR_FG_BOLD_BLUE}$@${COLOR_RESET}" 1>&2
 }
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check jq "search 'how to install jq'"
+combined_return=$(( combined_return + $? ))
+requirement_check git "search 'how to install git'"
+combined_return=$(( combined_return + $? ))
+requirement_check expect "search 'how to install expect'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 ADDITIONAL_USERS_GROUPS="flagship-productivity-reviewers"  # (comma-delimited)
-requirements=( jq expect )
-all_reqs_ok="true"
-for executable in "${requirements[@]}"; do
-  if [ ! $(command -v $executable) ]; then
-    echo_err "'$executable' is required but not installed"
-    all_reqs_ok="false"
-  fi
-done
-if [ "$all_reqs_ok" == "false" ]; then
-  exit 1
-fi
 branch_name=$(current_git_branch)
 review_id="$(git_review_board_id $branch_name)"
 if [ -n "$review_id" ]
diff --git a/scripts/lisubmit b/scripts/lisubmit
--- a/scripts/lisubmit
+++ b/scripts/lisubmit
@@ -176,6 +176,28 @@ echo_info ()
 {
     echo -e "${COLOR_FG_BOLD_BLUE}$@${COLOR_RESET}" 1>&2
 }
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check jq "search 'how to install jq'"
+combined_return=$(( combined_return + $? ))
+requirement_check find "search 'how to install find'"
+combined_return=$(( combined_return + $? ))
+requirement_check git "search 'how to install git'"
+combined_return=$(( combined_return + $? ))
+requirement_check curl "search 'how to install curl'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 in_mint_submit_repo() {
   if [ -f "$PWD/product-spec.json" ]; then
     submit_def="$(cat $PWD/product-spec.json | jq '.build.commands.submit')"
@@ -189,17 +211,6 @@ show_usage() {
   echo_err "Usage:"
   echo_err "  ${0##*/} <commit-msg> [, <commit-msg-extra-line>]"
 }
-requirements=( jq )
-all_reqs_ok="true"
-for executable in "${requirements[@]}"; do
-  if [ ! $(command -v $executable) ]; then
-    echo_err "'$executable' is required but not installed"
-    all_reqs_ok="false"
-  fi
-done
-if [ "$all_reqs_ok" == "false" ]; then
-  exit 1
-fi
 input_msg="$1"
 input_msg_extra_line="$2" # optional
 branch_name="$(current_git_branch)"
diff --git a/scripts/new_chrome b/scripts/new_chrome
--- a/scripts/new_chrome
+++ b/scripts/new_chrome
@@ -4,6 +4,24 @@
 # the file script-gen/new_chrome, and run './generate-scripts.sh'
 ###########################################################################
 
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check osascript "search 'how to install osascript'"
+combined_return=$(( combined_return + $? ))
+requirement_check pbpaste "search 'how to install pbpaste'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 clipboard_contents="$(pbpaste)"
 if [[ "$clipboard_contents" =~ ^http ]]
 then
diff --git a/scripts/new_firefox b/scripts/new_firefox
--- a/scripts/new_firefox
+++ b/scripts/new_firefox
@@ -4,5 +4,21 @@
 # the file script-gen/new_firefox, and run './generate-scripts.sh'
 ###########################################################################
 
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check osascript "search 'how to install osascript'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 osascript -e 'tell application "Firefox Nightly" to activate'
 osascript -e 'tell application "System Events" to keystroke "n" using command down'
diff --git a/scripts/new_ticket b/scripts/new_ticket
--- a/scripts/new_ticket
+++ b/scripts/new_ticket
@@ -10,6 +10,22 @@ echo_info ()
 {
     echo -e "${COLOR_FG_BOLD_BLUE}$@${COLOR_RESET}" 1>&2
 }
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check osascript "search 'how to install osascript'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 join() {
   local IFS="/"
   echo "$*"
diff --git a/scripts/send-email-from-api b/scripts/send-email-from-api
--- a/scripts/send-email-from-api
+++ b/scripts/send-email-from-api
@@ -4,6 +4,22 @@
 # the file script-gen/send-email-from-api, and run './generate-scripts.sh'
 ###########################################################################
 
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check sendEmail "search 'how to install sendEmail'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 to_email="${1:?First arg is the to: email address}"
 subject="${2:?Second arg is the subject}"
 message="${3:?Third arg is the message}"
@@ -11,9 +27,4 @@ GET_API_TOKEN="$HOME/Dropbox/secret/get-api-token"
 user="$($GET_API_TOKEN email-api-user)"
 pass="$($GET_API_TOKEN email-api-pass)"
 server="smtp.gmail.com:587"
-SEND_EMAIL="$( \
-  ([ -f /usr/local/bin/sendEmail ] && echo '/usr/local/bin/sendEmail') \
-  || ([ -f /usr/bin/sendEmail ] && echo '/usr/bin/sendEmail') \
-  || echo 'sendEmail' \
-)"
-$SEND_EMAIL -o tls=yes -f "$user" -t "$to_email" -s "$server" -xu "$user" -xp "$pass" -u "$subject" -m "$message"
+sendEmail -o tls=yes -f "$user" -t "$to_email" -s "$server" -xu "$user" -xp "$pass" -u "$subject" -m "$message"
diff --git a/scripts/send-email-from-outlook b/scripts/send-email-from-outlook
--- a/scripts/send-email-from-outlook
+++ b/scripts/send-email-from-outlook
@@ -4,6 +4,22 @@
 # the file script-gen/send-email-from-outlook, and run './generate-scripts.sh'
 ###########################################################################
 
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check sendEmail "search 'how to install sendEmail'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 to_email="${1:?First arg is the to: email address}"
 subject="${2:?Second arg is the subject}"
 email_contents="${3:?Third arg is the email contents}"
@@ -12,9 +28,4 @@ from_addr="$($GET_API_TOKEN outlook-email)"
 user="$($GET_API_TOKEN outlook-user)"
 pass="$($GET_API_TOKEN outlook-pass)"
 outlook_smtp='smtp-mail.outlook.com:587'
-SEND_EMAIL="$( \
-  ([ -f /usr/local/bin/sendEmail ] && echo '/usr/local/bin/sendEmail') \
-  || ([ -f /usr/bin/sendEmail ] && echo '/usr/bin/sendEmail') \
-  || echo 'sendEmail' \
-)"
-$SEND_EMAIL -o tls=yes -f "$from_addr" -t "$to_email" -s "$outlook_smtp" -xu "$user" -xp "$pass" -u "$subject" -m "$email_contents"
+sendEmail -o tls=yes -f "$from_addr" -t "$to_email" -s "$outlook_smtp" -xu "$user" -xp "$pass" -u "$subject" -m "$email_contents"
diff --git a/scripts/stock b/scripts/stock
--- a/scripts/stock
+++ b/scripts/stock
@@ -6,6 +6,22 @@
 
 COLOR_FG_RED='\033[0;31m'
 COLOR_RESET='\033[0m'
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check open "search 'how to install open'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 err_no_symbol="$(echo -e "${COLOR_FG_RED}Error: No stock symbol provided${COLOR_RESET}")"
 stock_symbol="${1:?$err_no_symbol}"
 stock_url="https://finance.yahoo.com/quote/$stock_symbol/"
diff --git a/scripts/todo b/scripts/todo
--- a/scripts/todo
+++ b/scripts/todo
@@ -6,6 +6,26 @@
 
 COLOR_FG_BOLD_BLUE='\033[1;34m'
 COLOR_RESET='\033[0m'
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check wc "search 'how to install wc'"
+combined_return=$(( combined_return + $? ))
+requirement_check grep "search 'how to install grep'"
+combined_return=$(( combined_return + $? ))
+requirement_check tr "search 'how to install tr'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 in_dir="${1:-.}" # default to current directory
 hash_comments='#'         # Python, Bash, Ruby, Perl
 slash_comments='//'       # C/C++, Javascript, Java, PHP
diff --git a/scripts/weather b/scripts/weather
--- a/scripts/weather
+++ b/scripts/weather
@@ -6,6 +6,28 @@
 
 COLOR_FG_BOLD_BLUE='\033[1;34m'
 COLOR_RESET='\033[0m'
+requirement_check ()
+{
+    local cmd="$1";
+    local how_to_install="$2";
+    if [ ! $(command -v $cmd) ]; then
+        echo_err "[ERROR] Command '$cmd' is required for this script, but not installed";
+        echo_err "To install: $how_to_install";
+        return 1;
+    else
+        return 0;
+    fi
+}
+combined_return=0
+requirement_check bc "search 'how to install bc'"
+combined_return=$(( combined_return + $? ))
+requirement_check jq "search 'how to install jq'"
+combined_return=$(( combined_return + $? ))
+requirement_check xargs "search 'how to install xargs'"
+combined_return=$(( combined_return + $? ))
+requirement_check curl "search 'how to install curl'"
+combined_return=$(( combined_return + $? ))
+if [ "$combined_return" != 0 ]; then exit $combined_return; fi
 zip_codes=( 94015 94043 94105 )
 for zip in ${zip_codes[*]}; do
   api_key="$($HOME/Dropbox/secret/get-api-token open-weather-map)"
