use RB title, and prompt for things before submitting

diff --git a/scripts/lisubmit b/scripts/lisubmit
--- a/scripts/lisubmit
+++ b/scripts/lisubmit
@@ -182,39 +182,93 @@ squash_commits() {
   return 0;
 }
 
+# trim leading and trailing double quotes
+trim_double_quotes() {
+  local string="$1"
+  string="${string#\"}"
+  string="${string%\"}"
+  echo "$string"
+}
+
+# get the API definition for review board at LinkedIn
+get_li_rb_api_def() {
+  local api_def=""
+  local cache_file="$DOTFILES_DIR/cache/li-rb-api-def.cache"
+  local cache_file_expired="$(find $cache_file -mtime +1)" # if cache file is older than 1 day
+
+  if [ -n "$cache_file_expired" ]; then
+    echoerr "not cached, requesting..."
+    api_def="$(curl -X GET -H 'Accept: application/json' 'https://rb.corp.linkedin.com/api/' 2>/dev/null)"
+    # TODO check return code for error
+    echo "$api_def" > "$cache_file"
+  else
+    api_def=$(<"$cache_file")
+  fi
+  echo "$api_def"
+}
+
+# get the template to use for querying the RB api
+get_li_rb_uri_template() {
+  local template="$(get_li_rb_api_def | jq ".uri_templates.$1")"
+  echo "$(trim_double_quotes $template)"
+}
+
+# get RB title
+get_li_rb_title() {
+  if [ -n "$1" ]; then
+    local api_uri_template=$(get_li_rb_uri_template "review_request")
+    local request_url=${api_uri_template/\{review_request_id\}/$1}
+    if [ -n "$request_url" ]
+    then
+      local summary=$(curl -X GET -H 'Accept: application/json' "$request_url" 2>/dev/null | jq '.review_request.summary')
+      echo "$(trim_double_quotes "$summary")"
+    fi
+  fi
+}
+
 
 # required things
 # TODO: jq
 
 # arguments
-commit_msg="$1"
-commit_msg_extra_line="$2" # optional
+input_msg="$1"
+input_msg_extra_line="$2" # optional
 
-if [ -z "$commit_msg" ]
-then
-  echo_err "ERROR: Missing commit message"
-  show_usage
+
+branch_name="$(current_git_branch)"
+
+review_id="$(git_review_board_id $branch_name)"
+if [ "$?" -ne 0 ]; then
+  echo_err "Dang it! Getting the review board ID failed"
   exit 1
 fi
+echo_info "Submitting RB $review_id"
+
+review_title="$(get_li_rb_title $review_id)"
+if [ -z "$input_msg" ]
+then
+  # use the title from the RB
+  input_msg="$review_title"
+fi
+
+# prompt for things
+echo -n "Commit message [$input_msg]: "
+read commit_msg
+if [ -z "$commit_msg" ]; then commit_msg="$input_msg"; fi
+
+echo -n "Commit message 2nd line (for PCLOVERRIDE, etc.) [$input_msg_extra_line]: "
+read commit_msg_extra_line
+if [ -z "$commit_msg_extra_line" ]; then commit_msg_extra_line="$input_msg_extra_line"; fi
 
 
 if in_git_repo && not_on_git_branch 'master' && no_uncommitted_changes
 then
-  branch_name=$(current_git_branch)
-
   # squash changes on this branch
   squash_branch "$commit_msg" "$commit_msg_extra_line"
   if [ "$?" -ne 0 ]; then
     echo_err "Dang it! squashing failed (TODO: auto recovery here?)"
     exit 1
   fi
-
-  review_id="$(git_review_board_id $branch_name)"
-  if [ "$?" -ne 0 ]; then
-    echo_err "Dang it! Getting the review board ID failed"
-    exit 1
-  fi
-  echo_info "Review ID: $review_id"
 
   # rebase against master
   do_git pull --rebase origin master && do_git checkout master && do_git pull --rebase
