show message on exit

diff --git a/scripts/lisubmit b/scripts/lisubmit
--- a/scripts/lisubmit
+++ b/scripts/lisubmit
@@ -215,9 +215,11 @@ input_msg="$1"
 input_msg_extra_line="$2" # optional
 branch_name="$(current_git_branch)"
 review_id="$(git_review_board_id $branch_name)"
-if [ "$?" -ne 0 ]; then
-  echo_err "Dang it! Getting the review board ID failed"
-  exit 1
+exit_code="$?"
+if [ "$exit_code" -ne 0 ]
+then
+  echo -e "${COLOR_FG_RED}Dang it! Getting the review board ID failed${COLOR_RESET}" >&2
+  exit "$exit_code"
 fi
 echo_info "Submitting RB $review_id"
 review_title="$(get_li_rb_title $review_id)"
@@ -245,9 +247,11 @@ if [ -z "$commit_msg_extra_line" ]; then commit_msg_extra_line="$input_msg_extra
 if in_git_repo && not_on_git_branch 'master' && no_uncommitted_changes
 then
   squash_branch "$commit_msg" "$commit_msg_extra_line"
-  if [ "$?" -ne 0 ]; then
-    echo_err "Dang it! squashing failed (TODO: auto recovery here?)"
-    exit 1
+  exit_code="$?"
+  if [ "$exit_code" -ne 0 ]
+  then
+    echo -e "${COLOR_FG_RED}Dang it! squashing failed (TODO: auto recovery here?)${COLOR_RESET}" >&2
+    exit "$exit_code"
   fi
   do_git pull --rebase origin master && do_git checkout master && do_git pull --rebase
   while [ "$?" -ne 0 ]; do
