fix lint issues from shellcheck/eslint/rubocop

diff --git a/scripts/process-bandcamp-zips b/scripts/process-bandcamp-zips
--- a/scripts/process-bandcamp-zips
+++ b/scripts/process-bandcamp-zips
@@ -1,4 +1,6 @@
-#!/usr/bin/env bash
+#!/usr/bin/env badash
+# shellcheck shell=bash
+
 # For albums I download from bandcamp
 # - unzip,
 # - add metadata for copyright and URL,
@@ -21,73 +23,15 @@ COPYRIGHTS['CC BY-NC 3.0']='Attribution-NonCommercial: http://creativecommons.or
 
 
 # display errors and info
-COLOR_FG_BOLD_BLUE='\033[1;34m'
-COLOR_FG_RED='\033[0;31m'
-COLOR_RESET='\033[0m'
-
 echo_error() {
-  #echo -e "${COLOR_FG_RED}$@${COLOR_RESET}" 1>&2
-  echo "[error] $@" 1>&2
+  echo "[error] $*" 1>&2
 }
-
 echo_info() {
-  #echo -e "${COLOR_FG_BOLD_BLUE}$@${COLOR_RESET}" 1>&2
-  echo "[info] $@" 1>&2
+  echo "[info] $*" 1>&2
 }
 
 # TODO: should I log all of this somewhere?
 # (to a known location in my home dir? temp dir? current dir? not sure...)
-
-# temp files to capture async function stdout, stderr, and exit code
-ASYNC_STDOUT="$(mktemp "$TMPDIR/$PROGRAM_NAME.stdout.XXXXXX")"
-ASYNC_STDERR="$(mktemp "$TMPDIR/$PROGRAM_NAME.stderr.XXXXXX")"
-ASYNC_EXIT_CODE="$(mktemp "$TMPDIR/$PROGRAM_NAME.exit-code.XXXXXX")"
-touch "$ASYNC_STDOUT" "$ASYNC_STDERR" "$ASYNC_EXIT_CODE"
-
-# use process substitution to run the input command asynchronously
-run_async() {
-  # $@ is all the args passed to this function
-  # TODO: also log this?
-  echo_info "(CMD) $@"
-
-  # print stdout to ASYNC_STDOUT, stderr to ASYNC_STDERR, and exit code to ASYNC_EXIT_CODE
-  { "$@" 1>"$ASYNC_STDOUT" 2>"$ASYNC_STDERR"; echo "$?" >"$ASYNC_EXIT_CODE"; } &
-}
-
-
-# show a busy spinner while the input PID is running, to clean up the output
-spin_wait() {
-  # arguments
-  cmd_pid="$1" # PID of the long-running command
-  spin_msg="$2" # Text to display along with the spinner animation
-
-  spin_chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' # braille dots
-  num_chars=${#spin_chars}
-  total_length=$(( 2 + ${#spin_msg} ))
-
-  # show a spinner with the spin_msg every 1/10th second while the process is running
-  i=0
-  while kill -0 $cmd_pid 2>/dev/null
-  do
-    i=$(( (i + 1) % num_chars ))
-    printf "\r${spin_chars:$i:1} ${spin_msg}" >&2
-    sleep 0.1
-  done
-
-  # get the exit code of that process (from the temp file)
-  exit_code="$(cat <"$ASYNC_EXIT_CODE")"
-
-  # print [OK] or [FAIL] along with the spin text
-  if [ "$exit_code" -eq 0 ]
-  then
-    printf "\r${spin_msg} [OK]\n" >&2
-  else
-    printf "\r${spin_msg} [FAIL]\n" >&2
-  fi
-
-  # return the exit code of the input PID
-  return "$exit_code"
-}
 
 # how to use this
 print_usage() {
@@ -109,7 +53,7 @@ prompt_for_copyright() {
   echo "" 1>&2
   echo "Which copyright does '$for_artist' use?" 1>&2
 
-  for(( i = 0; i < $num_items; i++ ))
+  for(( i = 0; i < num_items; i++ ))
   do
     # dislplay a 1-based index, which is nicer to select
     echo -e "[$(( i + 1 ))] ${menu_items_by_index[$i]}" 1>&2
@@ -118,7 +62,7 @@ prompt_for_copyright() {
   echo "" 1>&2
   echo -n "Selection: " 1>&2
 
-  read item_num
+  read -r item_num
   if [ -n "$item_num" ] && (( "$item_num" <= "$num_items" ))
   then
     (( item_index = item_num - 1 ))
@@ -145,7 +89,7 @@ prompt_for_url() {
   echo "What URL to use for '$for_artist'?" 1>&2
   echo -n "> " 1>&2
 
-  read input_url
+  read -r input_url
   if [ -n "$input_url" ]
   then
     # output the URL to write to the files
@@ -158,7 +102,7 @@ prompt_for_url() {
 
 # check for required commands
 req_check() {
-  if [ ! $(command -v $2) ]; then
+  if [ ! "$(command -v "$2")" ]; then
     echo "Required command '$2' not found" >&2
     printf -v "$1" "1"
   fi
@@ -188,9 +132,6 @@ if [ "$cmd_check_rtn" != 0 ]; then exit $cmd_check_rtn; fi
 
 # delete any remaining temp files and directories
 cleanup_temp() {
-  echo_info "(exit) cleaning up temp files"
-  rm "$ASYNC_STDOUT" "$ASYNC_STDERR" "$ASYNC_EXIT_CODE"
-
   if [ -n "$temp_dir" ]
   then
     echo_info "(exit) cleaning up temp dir '$temp_dir'..."
@@ -229,34 +170,28 @@ do
   echo_info "Created temp dir '$temp_dir'"
 
   # `unzip` to that temp directory
-  run_async unzip "$zip_file" -d "$temp_dir"
-  spin_wait $! "Extracting files..."
-  if [ "$?" -ne 0 ]
+  if ! @wait-for-command unzip "$zip_file" -d "$temp_dir"
   then
     echo_error "Failed to unzip '$zip_file'"
-    echo_info "stdout:"
-    echo "$(cat <"$ASYNC_STDOUT")"
-    echo_info "stderr:"
-    echo "$(cat <"$ASYNC_STDERR")"
     exit 1
   fi
 
   # initialize before the loop
   output_dir=""
 
-  unzip_output="$(cat <"$ASYNC_STDOUT")"
-  # figure out how many files were extracted
-  num_extracted_files="$(echo "$unzip_output" | grep -e 'extracting:' -e 'inflating:' | wc -l | tr -d '[:space:]')"
-  echo_info "Extracted $num_extracted_files files"
-  if [ "$num_extracted_files" -eq 0 ]
-  then
-    echo_error "Extracted 0 files"
-    echo_info "stdout:"
-    echo "$(cat <"$ASYNC_STDOUT")"
-    echo_info "stderr:"
-    echo "$(cat <"$ASYNC_STDERR")"
-    exit 1
-  fi
+  # unzip_output="$(cat <"$ASYNC_STDOUT")"
+  # # figure out how many files were extracted
+  # num_extracted_files="$(echo "$unzip_output" | grep -c -e 'extracting:' -e 'inflating:' | tr -d '[:space:]')"
+  # echo_info "Extracted $num_extracted_files files"
+  # if [ "$num_extracted_files" -eq 0 ]
+  # then
+  #   echo_error "Extracted 0 files"
+  #   echo_info "stdout:"
+  #   echo "$(cat <"$ASYNC_STDOUT")"
+  #   echo_info "stderr:"
+  #   echo "$(cat <"$ASYNC_STDERR")"
+  #   exit 1
+  # fi
 
   # process each FLAC file in that dir
   for flac_file in "$temp_dir"/*.flac
@@ -292,8 +227,11 @@ do
 
     # clean those up for use in the filename
     # (filter out '/' '\' ':' '|' '*' characters, and normalize track number to 2 digits)
+    # shellcheck disable=SC2001
     song_artist_fmt="$(echo "$song_artist" | sed 's"[/\:|*]"-"g')"
+    # shellcheck disable=SC2001
     song_album_fmt="$(echo "$song_album" | sed 's"[/\:|*]"-"g')"
+    # shellcheck disable=SC2001
     song_title_fmt="$(echo "$song_title" | sed 's"[/\:|*]"-"g')"
     song_track_fmt="$(printf "%02d" "$song_track")"
     echo_info "(formatted) Artist='$song_artist_fmt', Album='$song_album_fmt', Title='$song_title_fmt', Track='$song_track_fmt'"
@@ -335,15 +273,9 @@ do
     echo_info "intermediate metadata file: '$flac_metadata_file'"
 
     # add the URL and copyright info to the file
-    run_async ffmpeg -i "$flac_file" -metadata copyright="$song_copyright_fmt" -metadata url="$song_url_fmt" -codec copy "$flac_metadata_file"
-    spin_wait $! "Adding metadata..."
-    if [ "$?" -ne 0 ]
+    if ! @wait-for-command ffmpeg -i "$flac_file" -metadata copyright="$song_copyright_fmt" -metadata url="$song_url_fmt" -codec copy "$flac_metadata_file"
     then
       echo_error "Failed to add metadata"
-      echo_info "stdout:"
-      echo "$(cat <"$ASYNC_STDOUT")"
-      echo_info "stderr:"
-      echo "$(cat <"$ASYNC_STDERR")"
       exit 1
     fi
     echo_info "wrote file '$file_base-METADATA.$file_ext'"
@@ -354,15 +286,9 @@ do
 
     # normalize and convert
     # (using --force to force overwrite of existing files)
-    run_async ffmpeg-normalize "$flac_metadata_file" --video-disable --force --audio-codec libopus --audio-bitrate 128k -o "$final_output_file"
-    spin_wait $! "Converting to opus and normalizing..."
-    if [ "$?" -ne 0 ]
+    if ! @wait-for-command ffmpeg-normalize "$flac_metadata_file" --video-disable --force --audio-codec libopus --audio-bitrate 128k -o "$final_output_file"
     then
       echo_error "Failed to normalize and convert"
-      echo_info "stdout:"
-      echo "$(cat <"$ASYNC_STDOUT")"
-      echo_info "stderr:"
-      echo "$(cat <"$ASYNC_STDERR")"
       exit 1
     fi
     echo_info "wrote file '$song_track_fmt - $song_title_fmt.opus'"
@@ -389,8 +315,7 @@ do
 
   # cleanup:
   # delete the temp dir (not using rm since this should be empty)
-  rmdir "$temp_dir"
-  if [ "$?" -ne 0 ]
+  if ! rmdir "$temp_dir"
   then
     echo ""
     echo_error "Could not remove directory $temp_dir"
@@ -403,7 +328,7 @@ do
 
   # delete the input ZIP file (prompt for this, and assume no)
   echo -n "Delete the input file '$zip_file'? [y/N] "
-  read delete_input_file
+  read -r delete_input_file
   if [ "$delete_input_file" == "y" ] || [ "$delete_input_file" == "Y" ]
   then
     rm "$zip_file"
